theme: jekyll-theme-cayman
title: docs.oneconsultation.net
description: Technical documentation for OneConsultation
url: "https://modalitysystems.github.io/oneconsultation-docs"
baseurl: "/oneconsultation-docs"
plugins:
  - jemoji
