theme: jekyll-theme-cayman
title: docs.oneconsultation.net
description: Technical documentation for OneConsultation
url: "https://docs.oneconsultation.net/"
baseurl: "/oneconsultation-docs"
plugins:
  - jemoji
